[package]
name              = "adad-gate"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "Adad Gate — ingestion entry point"

[dependencies]
bahyway-core    = { path = "../bahyway-core" }
enkidb-kaki     = { path = "../enkidb-kaki" }
enkidb-engine   = { path = "../enkidb-engine" }
enkidb-journal  = { path = "../enkidb-journal" }
