[package]
name              = "permanent-storage"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "PERMANENT Golden Records storage"

[dependencies]
bahyway-core    = { path = "../bahyway-core" }
enkidb-kaki     = { path = "../enkidb-kaki" }
enkidb-engine   = { path = "../enkidb-engine" }
enkidb-journal  = { path = "../enkidb-journal" }
story-engine    = { path = "../story-engine" }
