[package]
name              = "vgca-validation"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "VGCA validation beam station"

[dependencies]
bahyway-core    = { path = "../bahyway-core" }
enkidb-kaki     = { path = "../enkidb-kaki" }
template-engine = { path = "../template-engine" }
enkidb-journal  = { path = "../enkidb-journal" }
