[package]
name              = "dubsar-ide"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "DubSar IDE main (VSCodium integration)"

[dependencies]
bahyway-core  = { path = "../bahyway-core" }
heptascript   = { path = "../heptascript" }
aaol          = { path = "../aaol" }
template-engine = { path = "../template-engine" }
