[package]
name              = "enkidb-ingest"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "CSV → Particle → EnkiDb ingestion pipeline (no external deps)"

[dependencies]
bahyway-core     = { path = "../bahyway-core" }
bahyway-crc      = { path = "../bahyway-crc" }
enkidb-kaki      = { path = "../enkidb-kaki" }
akkvalue         = { path = "../akkvalue" }
enkidb-particles = { path = "../enkidb-particles" }
enkidb-engine    = { path = "../enkidb-engine" }
enkidb-journal   = { path = "../enkidb-journal" }
enkidb-con-engine = { path = "../enkidb-con-engine" }
