[package]
name              = "enkidb-recovery"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "Crash Recovery and Abrupt-Termination handler"

[dependencies]
bahyway-core    = { path = "../bahyway-core" }
enkidb-kaki     = { path = "../enkidb-kaki" }
enkidb-journal  = { path = "../enkidb-journal" }
enkidb-snapshot = { path = "../enkidb-snapshot" }
