[package]
name              = "najaf-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "NajafEngine v4.0 — Wadi al-Salam sovereign cemetery navigation · 7-sector · Pilgrim routing"

[dependencies]
bahyway-core = { path = "../bahyway-core" }
enkidb-kaki  = { path = "../enkidb-kaki" }
navi-engine  = { path = "../navi-engine" }
