[package]
name              = "enkidb-particles"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "EnkiDB 7D EAV Particle — the sovereign unit of all stored knowledge"

[dependencies]
bahyway-core  = { path = "../bahyway-core" }
enkidb-kaki   = { path = "../enkidb-kaki" }
akkvalue      = { path = "../akkvalue" }
