[package]
name              = "enkidb-storage"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "Native storage primitives: mmap, fsync barriers"

[dependencies]
bahyway-core = { path = "../bahyway-core" }
bahyway-crc  = { path = "../bahyway-crc" }
enkidb-block = { path = "../enkidb-block" }
enkidb-kaki  = { path = "../enkidb-kaki" }
