[package]
name              = "enkidb-snapshot"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "Snapshot mechanism for point-in-time recovery"

[dependencies]
bahyway-core     = { path = "../bahyway-core" }
enkidb-kaki      = { path = "../enkidb-kaki" }
enkidb-journal   = { path = "../enkidb-journal" }
enkidb-vector-id = { path = "../enkidb-vector-id" }
