[package]
name              = "compare-tribe-schema"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "Compare_Tribe_Schema validation station"

[dependencies]
bahyway-core    = { path = "../bahyway-core" }
template-engine = { path = "../template-engine" }
bahyway-algebra = { path = "../bahyway-algebra" }
