[package]
name              = "eridu-runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "UrOS runtime daemon"

[dependencies]
bahyway-core      = { path = "../bahyway-core" }
enkidb-engine     = { path = "../enkidb-engine" }
eridu-scheduler   = { path = "../eridu-scheduler" }
enkisdb        = { path = "../enkisdb" }
enkiodb        = { path = "../enkiodb" }
enkiqdb        = { path = "../enkiqdb" }
enkidb-journal    = { path = "../enkidb-journal" }
enkidb-kaki       = { path = "../enkidb-kaki" }
storage-sector    = { path = "../storage-sector" }
blackbox-station  = { path = "../blackbox-station" }
