[package]
name              = "story-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "StoryEngine — CQRS read-side projection"

[dependencies]
bahyway-core     = { path = "../bahyway-core" }
enkidb-kaki      = { path = "../enkidb-kaki" }
enkidb-journal   = { path = "../enkidb-journal" }
enkidb-snapshot  = { path = "../enkidb-snapshot" }
enkidb-indexes   = { path = "../enkidb-indexes" }
