[package]
name              = "enkidb-journal"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "Append-only Journal — sovereignty event log"

[dependencies]
bahyway-core   = { path = "../bahyway-core" }
bahyway-crc    = { path = "../bahyway-crc" }
enkidb-kaki    = { path = "../enkidb-kaki" }
enkidb-storage = { path = "../enkidb-storage" }
