//! 𒁾 AkkBackend — The Sovereign Emission Protocol
//!
//! Built-in backends:
//!   `DebugBackend`   — pretty-prints the IR tree for inspection
//!   `AkkGenBackend`  — regenerates .akk source from IR (self-generative)
//!   `RustHintBackend`— emits Rust struct/impl skeletons

use crate::ir::AkkIr;
use crate::node::*;
use crate::errors::IrError;

// ── The Sovereign Backend Trait ───────────────────────────────────────────────

pub trait AkkBackend {
    type Output;
    type Error;

    fn emit_ir(&self, ir: &AkkIr) -> Result<Self::Output, Self::Error>;
    fn emit_node(&self, node: &AkkNode) -> Result<Self::Output, Self::Error>;
    fn name(&self) -> &'static str;
    fn supports_generation(&self) -> bool { false }
}

// ── Debug Backend ─────────────────────────────────────────────────────────────

pub struct DebugBackend { pub show_ids: bool, pub show_spans: bool }

impl Default for DebugBackend {
    fn default() -> Self { Self { show_ids: true, show_spans: false } }
}

impl AkkBackend for DebugBackend {
    type Output = String;
    type Error  = IrError;

    fn name(&self) -> &'static str { "debug" }

    fn emit_ir(&self, ir: &AkkIr) -> Result<String, IrError> {
        if ir.is_empty() { return Err(IrError::EmptyIr); }
        let mut out = format!("// 𒁾 AkkIr Debug — {}\n// {}\n\n", ir.source, ir.summary());
        for node in ir.nodes() { out.push_str(&self.emit_node(node)?); out.push('\n'); }
        Ok(out)
    }

    fn emit_node(&self, node: &AkkNode) -> Result<String, IrError> {
        let id_str   = if self.show_ids   { format!(" [{}]", node.id())   } else { String::new() };
        let span_str = if self.show_spans { format!(" <{}>", node.span()) } else { String::new() };
        Ok(format!("{} {}{}{} {{ {} children }}\n",
            node.kind_keyword(), node.name(), id_str, span_str, node.child_count()))
    }
}

// ── AkkGen Backend (self-generative) ─────────────────────────────────────────

pub struct AkkGenBackend;

impl AkkBackend for AkkGenBackend {
    type Output = String;
    type Error  = IrError;

    fn name(&self) -> &'static str { "akk_gen" }
    fn supports_generation(&self) -> bool { true }

    fn emit_ir(&self, ir: &AkkIr) -> Result<String, IrError> {
        if ir.is_empty() { return Err(IrError::EmptyIr); }
        let mut out = format!("// 𒁾 Generated by AkkGenBackend — {}\n// IR version: {}\n\n",
            ir.source, ir.ir_version);
        for node in ir.nodes() { out.push_str(&self.emit_node(node)?); out.push('\n'); }
        Ok(out)
    }

    fn emit_node(&self, node: &AkkNode) -> Result<String, IrError> {
        match node {
            AkkNode::Particle(p) => Ok(emit_particle(p)),
            AkkNode::Tribe(t)    => Ok(emit_tribe(t)),
            AkkNode::Rule(r)     => Ok(emit_rule(r)),
            AkkNode::Equation(e) => Ok(emit_equation(e)),
            AkkNode::Flow(f)     => Ok(emit_flow(f)),
            AkkNode::Observe(o)  => Ok(emit_observe(o)),
            AkkNode::Emit(e)     => Ok(emit_emit(e)),
            AkkNode::Guard(g)    => Ok(format!("GUARD {} {{ ... }}", g.name)),
            AkkNode::Pipeline(p) => {
                let mut s = format!("PIPELINE {} v{} {{\n", p.name, p.version);
                for child in &p.nodes { s.push_str(&format!("  {}\n", self.emit_node(child)?)); }
                s.push_str("}\n");
                Ok(s)
            }
        }
    }
}

fn emit_particle(p: &ParticleNode) -> String {
    let mut s = String::new();
    if let Some(ref doc) = p.doc { s.push_str(&format!("// {}\n", doc)); }
    s.push_str(&format!("PARTICLE {} {{\n", p.name));
    for field in &p.fields {
        let constraints: Vec<String> = field.constraints.iter()
            .map(|c| format!("{}={:.2}", c.dimension.akk_keyword(), c.min_value))
            .collect();
        if constraints.is_empty() {
            s.push_str(&format!("  {}: {}\n", field.name, field.field_type));
        } else {
            s.push_str(&format!("  {}: {}({})\n", field.name, field.field_type, constraints.join(", ")));
        }
    }
    if let Some(ref t) = p.tribe_ref { s.push_str(&format!("  TRIBE: {}\n", t)); }
    s.push_str("}\n");
    s
}

fn emit_tribe(t: &TribeNode) -> String {
    let weights = t.weights.weights.iter().map(|w| format!("{w:.2}")).collect::<Vec<_>>().join(", ");
    format!("TRIBE {} {{\n  WEIGHTS: [{}]\n  IDEAL:   [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]\n}}\n", t.name, weights)
}

fn emit_rule(r: &RuleNode) -> String {
    let mut s = format!("RULE {} {{\n", r.name);
    for cond in &r.conditions { s.push_str(&format!("  WHEN {} {} ...\n", cond.lhs, cond.op.akk_syntax())); }
    for action in &r.actions {
        let a = match action {
            RuleAction::SetLane(lane)           => format!("  THEN LANE = {}", lane.akk_keyword()),
            RuleAction::EmitStory { label }     => format!("  THEN EMIT Story(\"{}\")", label),
            RuleAction::ReScore                 => "  THEN RESCORE".to_string(),
            RuleAction::SendToSteward { reason} => format!("  THEN STEWARD(\"{}\")", reason),
            _                                   => "  THEN ...".to_string(),
        };
        s.push_str(&a); s.push('\n');
    }
    s.push_str("}\n");
    s
}

fn emit_equation(e: &EquationNode) -> String {
    let terms = if e.terms.is_empty() {
        "I_phys + I_mem + I_learn".to_string()
    } else {
        e.terms.iter().map(|t| t.label.as_str()).collect::<Vec<_>>().join(" + ")
    };
    format!("EQUATION {} {{\n  df/dt = {}\n  // terms: {}\n}}\n", e.name, terms, e.terms.len())
}

fn emit_flow(f: &FlowNode) -> String {
    let source = match &f.source {
        FlowSource::Enki    { lane, tribe } => format!("Enki(lane={lane:?}, tribe={tribe:?})"),
        FlowSource::Vault   { path }        => format!("Vault(\"{path}\")"),
        FlowSource::FlowRef { flow }        => format!("FLOW {flow}"),
        FlowSource::Literal { count }       => format!("Literal({count})"),
    };
    let sink = match &f.sink {
        FlowSink::Enki              => "Enki".to_string(),
        FlowSink::Vault   { label } => format!("Vault(\"{label}\")"),
        FlowSink::FlowRef { flow }  => format!("FLOW {flow}"),
        FlowSink::Discard           => "DISCARD".to_string(),
    };
    format!("FLOW {} {{\n  SOURCE: {}\n  // {} stages\n  SINK: {}\n}}\n", f.name, source, f.stages.len(), sink)
}

fn emit_observe(o: &ObserveNode) -> String {
    let from = match &o.from {
        ObserveFrom::Tribe      { name }       => format!("TRIBE {name}"),
        ObserveFrom::Lane       { lane }       => format!("LANE {}", lane.akk_keyword()),
        ObserveFrom::DeadGrid   { tribe }      => format!("DEAD_GRID {tribe:?}"),
        ObserveFrom::Neighbors  { kaki, k }    => format!("NEIGHBORS({kaki}, k={k})"),
        ObserveFrom::KakiPrefix { prefix }     => format!("KAKI_PREFIX {prefix}"),
    };
    format!("OBSERVE {} {{\n  FROM: {}\n  // {} filters\n  LIMIT: {:?}\n}}\n",
        o.name, from, o.filters.len(), o.limit)
}

fn emit_emit(e: &EmitNode) -> String {
    let target = match &e.target {
        EmitTarget::SelfHeal            => "SELF_HEAL",
        EmitTarget::SelfAlert           => "SELF_ALERT",
        EmitTarget::NewEquation         => "NEW_EQUATION",
        EmitTarget::StoryEvent          => "STORY_EVENT",
        EmitTarget::StorageLog          => "STORAGE_LOG",
        EmitTarget::UpdateRule { .. }   => "UPDATE_RULE",
        EmitTarget::Webhook    { .. }   => "WEBHOOK",
        EmitTarget::Report     { .. }   => "REPORT",
    };
    format!("EMIT {} {{\n  TARGET: {}\n  TEMPLATE: {:?}\n  PERSIST: {}\n}}\n",
        e.name, target, e.template, e.persist)
}

// ── Rust Hint Backend ─────────────────────────────────────────────────────────

pub struct RustHintBackend;

impl AkkBackend for RustHintBackend {
    type Output = String;
    type Error  = IrError;

    fn name(&self) -> &'static str { "rust_hint" }

    fn emit_ir(&self, ir: &AkkIr) -> Result<String, IrError> {
        let mut out = String::from("// 𒁾 Rust Backend Hints\n\n");
        for node in ir.nodes() { out.push_str(&self.emit_node(node)?); }
        Ok(out)
    }

    fn emit_node(&self, node: &AkkNode) -> Result<String, IrError> {
        match node {
            AkkNode::Particle(p) => Ok(format!(
                "/// Sovereign particle: {}\n#[derive(Debug, Clone)]\npub struct {} {{\n    pub kaki: [u8; 16],\n    pub b11: u8,\n    // {} fields\n}}\n\n",
                p.name, p.name, p.fields.len()
            )),
            AkkNode::Tribe(t) => Ok(format!(
                "/// Tribe ideal: {}\npub const {}_TRIBE: [f32; 7] = {:?};\n\n",
                t.name, t.name.to_uppercase(), t.weights.weights
            )),
            AkkNode::Rule(r) => Ok(format!(
                "/// Rule: {}\npub fn rule_{}(_p: &mut Particle) -> bool {{\n    // {} conditions, {} actions\n    todo!()\n}}\n\n",
                r.name, r.name.to_lowercase().replace(' ', "_"), r.conditions.len(), r.actions.len()
            )),
            _ => Ok(format!("// {} {}\n", node.kind_keyword(), node.name())),
        }
    }
}
