[package]
name              = "data-cleansing-station"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "Data Cleansing Station"

[dependencies]
bahyway-core    = { path = "../bahyway-core" }
template-engine = { path = "../template-engine" }
enkidb-journal  = { path = "../enkidb-journal" }
damadmbok-dictionary = { path = "../damadmbok-dictionary" }
vgca-engine          = { path = "../vgca-engine" }
bahyway-dqm          = { path = "../bahyway-dqm" }
