//! WayCompiler — compiles a `WayFile` into AAOL (.akk) source and validates it.
//!
//! The generated AAOL program declares:
//!   - The sovereign tribe
//!   - One actor per clearance level
//!   - The specified role
//!   - Event rules: arrival → emit snapshot; mutation → emit snapshot
//!
//! The output is validated by passing it through the AAOL parser so that
//! compile-time errors surface early.

use crate::way_file::WayFile;
use aaol::{tokenize, Parser};

/// Outcome of compiling a `.way` file.
#[derive(Debug)]
pub struct CompileResult {
    /// Generated AAOL (.akk) source.
    pub akk_source: String,
    /// Any parse warnings (not fatal).
    pub warnings: Vec<String>,
}

/// Compile a `WayFile` into validated AAOL source.
pub fn compile(way: &WayFile) -> Result<CompileResult, String> {
    let akk = generate_akk(way);

    // Validate by running through the AAOL parser
    let tokens = tokenize(&akk).map_err(|e| format!("tokenize: {e}"))?;
    let mut parser = Parser::new(tokens);
    parser.parse().map_err(|e| format!("parse: {e}"))?;

    Ok(CompileResult {
        akk_source: akk,
        warnings: Vec::new(),
    })
}

/// Generate AAOL source from a `WayFile` without validating.
pub fn generate_akk(way: &WayFile) -> String {
    let tribe_name = way.tribe_name();
    let actor_name = actor_name_for(&way.class);
    let role = &way.role;
    let sovereignty = &way.sovereignty;
    let clearance = way.clearance;

    // Actor name derived from sovereignty tag + clearance
    // e.g. PA-15 clearance 3 → "PA15L3"
    let cleared_actor = sovereignty_actor(sovereignty, clearance);

    format!(
        "# Generated by WayCompiler from {class}\n\
         # Sovereignty: {sovereignty}  Clearance: {clearance}\n\
         tribe {tribe_name} {{\n\
           actor {actor_name} {{\n\
             role {role}\n\
           }}\n\
           actor {cleared_actor} {{\n\
             role {role}\n\
           }}\n\
         }}\n\
         when event \"arrival\" then emit snapshot;\n\
         when event \"mutation\" then emit snapshot;\n",
        class = way.class,
        sovereignty = sovereignty,
        clearance = clearance,
        tribe_name = tribe_name,
        actor_name = actor_name,
        cleared_actor = cleared_actor,
        role = role,
    )
}

fn actor_name_for(class: &str) -> String {
    // Capitalise the last dot-separated segment and suffix with "Agent".
    // Known exceptions are handled by a small lookup table.
    match class {
        "civil.registry" | "registry" => return "Registrar".to_string(),
        _ => {}
    }
    let segment = class.rsplit('.').next().unwrap_or(class);
    let mut name: String = segment
        .chars()
        .enumerate()
        .map(|(i, c)| if i == 0 { c.to_ascii_uppercase() } else { c })
        .collect();
    name.push_str("Agent");
    name
}

fn sovereignty_actor(sovereignty: &str, clearance: u8) -> String {
    // "PA-15" → "PA15", then append "L<clearance>"
    let tag: String = sovereignty
        .chars()
        .filter(|c| c.is_alphanumeric())
        .collect();
    format!("{tag}L{clearance}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::way_file::WayFile;

    fn najaf_way() -> WayFile {
        WayFile::parse(
            "tribe 0x0001\nclass civil.registry\nsovereignty PA-15\nclearance 3\nrole Zikru",
        )
        .unwrap()
    }

    #[test]
    fn compile_produces_valid_aaol() {
        let way = najaf_way();
        let res = compile(&way).expect("compile should succeed");
        assert!(res.akk_source.contains("tribe CivilRegistry"));
        assert!(res.akk_source.contains("role Zikru"));
        assert!(res.akk_source.contains("when event"));
    }

    #[test]
    fn generated_akk_parses_clean() {
        let way = najaf_way();
        let res = compile(&way).unwrap();
        let tokens = aaol::tokenize(&res.akk_source).unwrap();
        let mut parser = aaol::Parser::new(tokens);
        parser
            .parse()
            .expect("generated AAOL must parse without errors");
    }

    #[test]
    fn actor_naming_for_known_classes() {
        assert_eq!(actor_name_for("civil.registry"), "Registrar");
        assert_eq!(actor_name_for("sensor.stream"), "StreamAgent");
        assert_eq!(actor_name_for("operational"), "OperationalAgent");
        assert_eq!(actor_name_for("data.pipeline"), "PipelineAgent");
    }
}
