//! Akkadian DSL v3.4 - SQL Generator
//! Generates PostgreSQL DDL from Akkadian AST
//! Direct port from SqlGenerator.cs
//! 
//! Author: Bahaa Fadam
//! BahyWay Sovereign Ecosystem

use crate::ast::*;
use std::fmt::Write;

// ============================================================================
// SQL GENERATOR
// ============================================================================

pub struct SqlGenerator;

impl SqlGenerator {
    /// Generate complete SQL DDL from Akkadian program
    pub fn generate(program: &AkkadianProgram) -> Result<String, std::fmt::Error> {
        let mut sql = String::new();
        
        writeln!(sql, "-- =============================================")?;
        writeln!(sql, "-- AKKADIAN GENERATED SQL (PostgreSQL / Data Vault)")?;
        writeln!(sql, "-- Generated by Akkadian.Compiler v3.4 (Rust)")?;
        writeln!(sql, "-- =============================================")?;
        writeln!(sql)?;
        
        for context in &program.contexts {
            writeln!(sql, "-- CONTEXT: {}", context.name)?;
            writeln!(sql, "CREATE SCHEMA IF NOT EXISTS {};", context.name)?;
            writeln!(sql)?;
            
            if let Some(storage) = &context.storage {
                // Generate Hubs
                for hub in &storage.hubs {
                    sql.push_str(&Self::generate_table(&context.name, hub)?);
                }
                
                // Generate Links
                for link in &storage.links {
                    sql.push_str(&Self::generate_table(&context.name, link)?);
                }
                
                // Generate Satellites
                for sat in &storage.satellites {
                    sql.push_str(&Self::generate_table(&context.name, sat)?);
                }
            }
        }
        
        Ok(sql)
    }
    
    /// Generate CREATE TABLE statement for a table node
    fn generate_table(schema: &str, table: &TableNode) -> Result<String, std::fmt::Error> {
        let mut sql = String::new();
        
        writeln!(sql, "-- {:?}: {}", table.table_type, table.name)?;
        writeln!(sql, "CREATE TABLE IF NOT EXISTS {}.{} (", schema, table.name)?;
        
        let mut lines = Vec::new();
        
        // 1. User-defined columns
        for col in &table.columns {
            let mut line = format!("    {} {}", col.name, Self::map_to_postgres_type(&col.data_type));
            
            if col.is_primary_key {
                line.push_str(" PRIMARY KEY");
                line.push_str(" NOT NULL");
            } else if col.is_unique {
                line.push_str(" UNIQUE");
            }
            
            lines.push(line);
        }
        
        // 2. Standard audit columns (Data Vault pattern)
        lines.push("    LoadDate TIMESTAMP DEFAULT NOW() NOT NULL".to_string());
        lines.push("    RecordSource VARCHAR(100) NOT NULL".to_string());
        
        // 3. Temporal tracking columns (if enabled)
        if table.has_temporal_tracking {
            lines.push("    ValidFrom TIMESTAMP DEFAULT NOW() NOT NULL".to_string());
            lines.push("    ValidTo TIMESTAMP NULL".to_string());
            lines.push("    IsCurrent BOOLEAN DEFAULT TRUE".to_string());
        }
        
        writeln!(sql, "{}", lines.join(",\n"))?;
        writeln!(sql, ");")?;
        
        // 4. Physical optimization: Clustering
        if let Some(ref clustered_by) = table.clustered_by {
            let idx_name = format!("idx_{}_cluster", table.name);
            writeln!(sql, "-- Optimization: Clustering by {}", clustered_by)?;
            writeln!(sql, "CREATE INDEX IF NOT EXISTS {} ON {}.{} USING BRIN ({});", 
                idx_name, schema, table.name, clustered_by)?;
            writeln!(sql, "CLUSTER {}.{} USING {};", schema, table.name, idx_name)?;
        }
        
        // 5. Additional indexes
        for (index_type, columns) in &table.indexes {
            let idx_name = format!("idx_{}_{}", table.name, columns.join("_"));
            let index_method = Self::map_index_type(index_type);
            writeln!(sql, "CREATE INDEX IF NOT EXISTS {} ON {}.{} USING {} ({});",
                idx_name, schema, table.name, index_method, columns.join(", "))?;
        }
        
        writeln!(sql)?;
        Ok(sql)
    }
    
    /// Map Akkadian data types to PostgreSQL types
    fn map_to_postgres_type(akkadian_type: &str) -> String {
        if akkadian_type.starts_with("VARCHAR") {
            return akkadian_type.to_string();
        }
        if akkadian_type.starts_with("DECIMAL") {
            return akkadian_type.to_string();
        }
        
        match akkadian_type {
            "UUID" => "UUID".to_string(),
            "INT" => "INTEGER".to_string(),
            "BIGINT" => "BIGINT".to_string(),
            "TIMESTAMP" => "TIMESTAMP".to_string(),
            "GEOMETRY" => "GEOMETRY".to_string(),
            "BOOLEAN" => "BOOLEAN".to_string(),
            _ => akkadian_type.to_string(),
        }
    }
    
    /// Map index type to PostgreSQL index method
    fn map_index_type(index_type: &str) -> &str {
        match index_type {
            "BTREE" => "BTREE",
            "HASH" => "HASH",
            "GIN" => "GIN",
            "GIST" => "GIST",
            "BRIN" => "BRIN",
            "SPGIST" => "SPGIST",
            _ => "BTREE", // Default
        }
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_simple_hub() {
        let mut program = AkkadianProgram::new();
        let mut context = ContextNode::new("TestContext".to_string());
        
        let mut storage = StorageNode::new();
        let mut hub = TableNode::new("PersonHub".to_string(), TableType::Hub);
        
        hub.columns.push(ColumnNode {
            name: "id".to_string(),
            data_type: "UUID".to_string(),
            is_primary_key: true,
            is_unique: false,
        });
        
        hub.columns.push(ColumnNode {
            name: "name".to_string(),
            data_type: "VARCHAR(100)".to_string(),
            is_primary_key: false,
            is_unique: false,
        });
        
        storage.hubs.push(hub);
        context.storage = Some(storage);
        program.contexts.push(context);
        
        let sql = SqlGenerator::generate(&program).unwrap();
        
        assert!(sql.contains("CREATE SCHEMA IF NOT EXISTS TestContext"));
        assert!(sql.contains("CREATE TABLE IF NOT EXISTS TestContext.PersonHub"));
        assert!(sql.contains("id UUID PRIMARY KEY"));
        assert!(sql.contains("name VARCHAR(100)"));
        assert!(sql.contains("LoadDate TIMESTAMP"));
        assert!(sql.contains("RecordSource VARCHAR(100)"));
    }

    #[test]
    fn test_generate_temporal_satellite() {
        let mut program = AkkadianProgram::new();
        let mut context = ContextNode::new("Test".to_string());
        
        let mut storage = StorageNode::new();
        let mut sat = TableNode::new("PersonDetails".to_string(), TableType::Satellite);
        sat.has_temporal_tracking = true;
        
        sat.columns.push(ColumnNode {
            name: "person_id".to_string(),
            data_type: "UUID".to_string(),
            is_primary_key: true,
            is_unique: false,
        });
        
        storage.satellites.push(sat);
        context.storage = Some(storage);
        program.contexts.push(context);
        
        let sql = SqlGenerator::generate(&program).unwrap();
        
        assert!(sql.contains("ValidFrom TIMESTAMP"));
        assert!(sql.contains("ValidTo TIMESTAMP"));
        assert!(sql.contains("IsCurrent BOOLEAN"));
    }

    #[test]
    fn test_type_mapping() {
        assert_eq!(SqlGenerator::map_to_postgres_type("UUID"), "UUID");
        assert_eq!(SqlGenerator::map_to_postgres_type("INT"), "INTEGER");
        assert_eq!(SqlGenerator::map_to_postgres_type("BIGINT"), "BIGINT");
        assert_eq!(SqlGenerator::map_to_postgres_type("VARCHAR(100)"), "VARCHAR(100)");
    }
}
