[package]
name              = "eridu-supervisor"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "EriduOS system supervisor / process management"

[dependencies]
bahyway-core     = { path = "../bahyway-core" }
eridu-runtime    = { path = "../eridu-runtime" }
eridu-scheduler  = { path = "../eridu-scheduler" }
