[package]
name              = "musaru-security"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "Musarû Security check station"

[dependencies]
bahyway-core    = { path = "../bahyway-core" }
enkidb-kaki     = { path = "../enkidb-kaki" }
enkidb-journal  = { path = "../enkidb-journal" }
