//! Symptom registry (Asû): R-01 CHECKSUM_DRIFT · R-02 EAV_MANDATORY_MISSING · R-03 HUE_VARIANCE · R-04 RIKSU_ORPHAN · R-05 STALE_TEMPORAL · FMT-01 FORMAT_REFUSAL
//! Cause registry (Āšipu): C-01 SOURCE_FEED_POISON · C-02 TEMPLATE_DEFECT · C-03 PASHIRU_CALIBRATION · C-04 RIKSU_SEVERANCE · C-05 RENEWAL_RITE_HALTED
//! Law: DETECT → PROVE → PREDICT → PRESCRIBE — no cure before cause; two witnesses always.
