[package]
name              = "data-structure-station"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "Data Structure Station"

[dependencies]
bahyway-core    = { path = "../bahyway-core" }
template-engine = { path = "../template-engine" }
enkidb-journal  = { path = "../enkidb-journal" }
