[package]
name              = "score-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "Quality scoring engine (ColorID computation)"

[dependencies]
bahyway-core   = { path = "../bahyway-core" }
enkidb-kaki    = { path = "../enkidb-kaki" }
enkidb-journal = { path = "../enkidb-journal" }
story-engine   = { path = "../story-engine" }
fuzzy-engine   = { path = "../fuzzy-engine" }
