[package]
name              = "snapshot-job"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "Snapshot_Job scheduler"

[dependencies]
bahyway-core     = { path = "../bahyway-core" }
enkidb-kaki      = { path = "../enkidb-kaki" }
enkidb-journal   = { path = "../enkidb-journal" }
enkidb-snapshot  = { path = "../enkidb-snapshot" }
enkidb-vector-id = { path = "../enkidb-vector-id" }
story-engine     = { path = "../story-engine" }
