//! A Tupsimati tablet decrees; a playbook enacts.
//!
//! Generates the numbered Ansible playbook that applies a sealed tablet to
//! the EnkiDB nodes. The Architect runs it (CSR-08). Refuses to generate
//! from an unsealed tablet.

use crate::Tablet;

pub fn emit_playbook(t: &Tablet, pb_number: u32) -> Result<String, String> {
    if t.seal.is_none() {
        return Err("unsealed tablet may not decree".into());
    }
    t.validate()?;
    let mut out = format!(
        "# PB-{n} — Apply Tupsimati tablet v{v} (generated)\n\
         # Generated by tupsimati::playbook — do not hand-edit;\n\
         # amend the tablet and regenerate.\n\
         - name: \"PB-{n} | Apply Tupsimati v{v}\"\n\
         \x20 hosts: enkidb_nodes\n\
         \x20 gather_facts: false\n\
         \x20 tasks:\n",
        n = pb_number,
        v = t.version
    );
    out += "    - name: \"Deploy tablet lines to nodes\"\n";
    out += "      ansible.builtin.copy:\n";
    out += &format!("        dest: /etc/bahyway/tupsimati-v{}.tab\n", t.version);
    out += "        mode: \"0644\"\n";
    out += "        content: |\n";
    for line in t.to_lines().lines() {
        out += &format!("          {line}\n");
    }
    // NOTE: mapping tablet lines onto actual enkidb config keys from
    // current source is separate, later work -- never guessed here.
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use kupru::SealKeyPair;

    #[test]
    fn refuses_to_emit_from_an_unsealed_tablet() {
        let t = Tablet {
            version: 1,
            created_millis: 0,
            ..Default::default()
        };
        assert!(emit_playbook(&t, 233).is_err());
    }

    #[test]
    fn emits_a_playbook_from_a_sealed_tablet() {
        let mut t = Tablet {
            version: 1,
            created_millis: 0,
            ..Default::default()
        };
        let key = SealKeyPair::generate().unwrap();
        t.seal_with(&key).unwrap();
        let pb = emit_playbook(&t, 233).unwrap();
        assert!(pb.contains("PB-233"));
        assert!(pb.contains("tupsimati-v1.tab"));
        assert!(pb.contains("do not hand-edit"));
    }
}
