[package]
name              = "istar"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "Istar — Sovereign access control and AkkadianAOL firewall engine"

[dependencies]
serde   = { version = "1",    features = ["derive"] }
tracing = { version = "0.1" }
