[package]
name              = "enkidb-indexes"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "All seven native EnkiDB indexes (one crate, 7 modules)"

[dependencies]
bahyway-core     = { path = "../bahyway-core" }
enkidb-kaki      = { path = "../enkidb-kaki" }
enkidb-snapshot  = { path = "../enkidb-snapshot" }
enkidb-vector-id = { path = "../enkidb-vector-id" }
