[package]
name              = "data-steward-station"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "Data Steward Station"

[dependencies]
bahyway-core         = { path = "../bahyway-core" }
alert-engine         = { path = "../alert-engine" }
diagnosis-templates  = { path = "../diagnosis-templates" }
enkidb-kaki          = { path = "../enkidb-kaki" }
enkidb-journal       = { path = "../enkidb-journal" }
enkisdb           = { path = "../enkisdb" }
enkiqdb           = { path = "../enkiqdb" }
enkiodb           = { path = "../enkiodb" }
storage-sector       = { path = "../storage-sector" }
