[package]
name              = "enkidb-query"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "Query execution against indexes and journal"

[dependencies]
bahyway-core   = { path = "../bahyway-core" }
bahyway-crc    = { path = "../bahyway-crc" }
akkvalue       = { path = "../akkvalue" }
enkidb-kaki    = { path = "../enkidb-kaki" }
enkidb-engine  = { path = "../enkidb-engine" }
enkidb-journal = { path = "../enkidb-journal" }
heptascript    = { path = "../heptascript" }
