[package]
name              = "enkidb-block"
version.workspace = true
edition.workspace = true
authors.workspace = true
description       = "64MB block-aligned cold storage format"

[dependencies]
bahyway-core = { path = "../bahyway-core" }
bahyway-crc  = { path = "../bahyway-crc" }
enkidb-kaki  = { path = "../enkidb-kaki" }
